package main

import (
	"encoding/json"
	"os"
	"reflect"
	"strings"
	"testing"
)

func TestAppSubDirs(t *testing.T) {
	cases := []struct {
		path string
		want string
	}{
		{"/p/src/main/mule/sub/f.xml", "/sub/"},
		{"/p/src/main/mule/a/b/f.xml", "/a/b/"},
		{"/p/src/main/mule/f.xml", ""},
		{"/p/src/main/resources/conf/f.yaml", "/conf/"},
		{"/p/unrelated/f.xml", ""},
	}
	for _, c := range cases {
		if got := appSubDirs(c.path); got != c.want {
			t.Errorf("appSubDirs(%q) = %q, want %q", c.path, got, c.want)
		}
	}
}

func TestExtractProjectRootFromPath(t *testing.T) {
	setOpts(t, defaultTestOpts())
	if got := extractProjectRootFromPath("/projects/app/src/main/mule/f.xml"); got != "/projects/app" {
		t.Errorf("got %q", got)
	}
	if got := extractProjectRootFromPath("/projects/app/src/main/resources/a/b.txt"); got != "/projects/app" {
		t.Errorf("got %q", got)
	}
	if got := extractProjectRootFromPath("/no/match/here.xml"); got != "" {
		t.Errorf("non-matching path should give empty root, got %q", got)
	}
}

func TestIgnoreFile(t *testing.T) {
	setOpts(t, defaultTestOpts())
	cases := []struct {
		file string
		want bool
	}{
		{"/p/target/classes/f.xml", true},
		{"/p/src/main/mule/f.xml.orig", true},
		{"/p/.git/config", true},
		{"/p/.mule/state", true},
		{"/p/src/main/mule/weave/autogenerated/x", true},
		{"/p/src/main/mule/flow.xml", false},
		{"/p/src/main/resources/app.properties", false},
	}
	for _, c := range cases {
		if got := ignoreFile(c.file); got != c.want {
			t.Errorf("ignoreFile(%q) = %v, want %v", c.file, got, c.want)
		}
	}
}

func TestIgnoreFileOnlyBelowProjectsDir(t *testing.T) {
	o := defaultTestOpts()
	o.ProjectsDir = "/home/alice/bin/mule-projects"
	setOpts(t, o)
	if ignoreFile("/home/alice/bin/mule-projects/app/src/main/mule/f.xml") {
		t.Error("ignore names in the projects dir prefix must not disable the tool")
	}
	if !ignoreFile("/home/alice/bin/mule-projects/app/target/f.xml") {
		t.Error("ignore names below the projects dir must still count")
	}
}

func TestSignificantChanges(t *testing.T) {
	setOpts(t, defaultTestOpts())
	dir := t.TempDir()
	w := func(name, content string) string {
		path := dir + "/" + name
		writeFile(t, path, content)
		return path
	}

	cases := []struct {
		name             string
		updated, current string
		want             bool
	}{
		{
			"xml formatting only",
			w("u1.xml", "<mule>\n    <flow name=\"a\"/>\n</mule>\n"),
			w("c1.xml", "<mule><flow name=\"a\"/></mule>"),
			false,
		},
		{
			"xml real change",
			w("u2.xml", `<mule><flow name="b"/></mule>`),
			w("c2.xml", `<mule><flow name="a"/></mule>`),
			true,
		},
		{
			"json key reorder",
			w("u3.json", `{"b": 2, "a": 1}`),
			w("c3.json", `{"a": 1, "b": 2}`),
			false,
		},
		{
			"json real change",
			w("u4.json", `{"a": 2}`),
			w("c4.json", `{"a": 1}`),
			true,
		},
		{
			"properties whitespace is significant",
			w("u5.properties", "key=a  b\n"),
			w("c5.properties", "key=a b\n"),
			true,
		},
		{
			"identical properties",
			w("u6.properties", "key=a\n"),
			w("c6.properties", "key=a\n"),
			false,
		},
		{
			"unparseable xml keeps deployed copy",
			w("u7.xml", "<mule><broken"),
			w("c7.xml", `<mule/>`),
			false,
		},
	}
	for _, c := range cases {
		if got := significantChanges(c.updated, c.current); got != c.want {
			t.Errorf("%s: significantChanges = %v, want %v", c.name, got, c.want)
		}
	}

	if !significantChanges(dir+"/nope.xml", dir+"/also-nope.xml") {
		t.Error("missing files must be significant")
	}
}

func TestSignificantChangesNoIgnoreFormatting(t *testing.T) {
	o := defaultTestOpts()
	o.IgnoreFormatting = false
	setOpts(t, o)
	dir := t.TempDir()
	writeFile(t, dir+"/u.xml", "<a/>")
	writeFile(t, dir+"/c.xml", "<a/>")
	if significantChanges(dir+"/u.xml", dir+"/c.xml") {
		t.Error("byte-identical files are never significant, even with --no-ignore-formatting")
	}
	writeFile(t, dir+"/c2.xml", "<a></a>") // same canonical form, different bytes
	if !significantChanges(dir+"/u.xml", dir+"/c2.xml") {
		t.Error("with --no-ignore-formatting formatting differences are significant")
	}
}

func TestSignificantChangesUnparseableDeployedCopy(t *testing.T) {
	setOpts(t, defaultTestOpts())
	dir := t.TempDir()
	// deployed copy corrupt, source good: must sync to repair it
	writeFile(t, dir+"/u.xml", "<mule/>")
	writeFile(t, dir+"/c.xml", "<mule><broken")
	if !significantChanges(dir+"/u.xml", dir+"/c.xml") {
		t.Error("a corrupt deployed copy must be repairable")
	}
	// both sides unparseable (e.g. unsupported encoding): exact comparison
	writeFile(t, dir+"/u2.xml", "<broken same")
	writeFile(t, dir+"/c2.xml", "<broken same")
	if significantChanges(dir+"/u2.xml", dir+"/c2.xml") {
		t.Error("identical unparseable files are not significant")
	}
	writeFile(t, dir+"/c3.xml", "<broken other")
	if !significantChanges(dir+"/u2.xml", dir+"/c3.xml") {
		t.Error("differing unparseable files must still sync")
	}
}

func TestSignificantChangesSizeThreshold(t *testing.T) {
	setOpts(t, defaultTestOpts())
	dir := t.TempDir()
	big := strings.Repeat("x", 1024*1024+1)
	writeFile(t, dir+"/u.txt", big)
	writeFile(t, dir+"/c.txt", big)
	if !significantChanges(dir+"/u.txt", dir+"/c.txt") {
		t.Error("files over 1MB skip comparison and count as significant")
	}
}

func TestContainsMonitorInterval(t *testing.T) {
	dir := t.TempDir()
	w := func(name, content string) string {
		path := dir + "/" + name
		writeFile(t, path, content)
		return path
	}
	if !containsMonitorInterval(w("a.xml", `<Configuration monitorInterval="10"><Appenders/></Configuration>`)) {
		t.Error("monitorInterval attribute should be detected")
	}
	if containsMonitorInterval(w("b.xml", `<Configuration><Appenders/></Configuration>`)) {
		t.Error("no monitorInterval attribute")
	}
	if containsMonitorInterval(w("c.xml", `<Other monitorInterval="10"/>`)) {
		t.Error("root element must be Configuration")
	}
	if containsMonitorInterval(w("d.xml", `<broken`)) {
		t.Error("unparseable file has no monitorInterval")
	}
}

func TestRelativeFiles(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir+"/a.xml", "")
	writeFile(t, dir+"/sub/b.xml", "")
	writeFile(t, dir+"/c.txt", "")
	writeFile(t, dir+"/.DS_Store", "")
	writeFile(t, dir+"/.hidden/d.xml", "")

	xmls, err := relativeFiles(dir+"/", ".xml")
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(xmls, []string{"a.xml", "sub/b.xml"}) {
		t.Errorf("xml files = %v", xmls)
	}
	all, err := relativeFiles(dir+"/", "")
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(all, []string{"a.xml", "c.txt", "sub/b.xml"}) {
		t.Errorf("all files = %v (dotfiles must be excluded)", all)
	}

	missing, err := relativeFiles(dir+"/nope/", "")
	if err != nil || len(missing) != 0 {
		t.Errorf("missing dir should give empty list, got (%v, %v)", missing, err)
	}
}

func TestRebuildMuleArtifact(t *testing.T) {
	setOpts(t, defaultTestOpts())
	dir := t.TempDir()
	project := dir + "/proj"
	app := dir + "/app"
	writeFile(t, project+"/src/main/mule/flow.xml", "<mule/>")
	writeFile(t, project+"/src/main/mule/sub/other.xml", "<mule/>")
	writeFile(t, project+"/src/main/resources/app.properties", "")
	writeFile(t, project+"/src/main/resources/.DS_Store", "")
	writeFile(t, app+"/META-INF/mule-artifact/mule-artifact.json",
		`{"name":"proj","configs":[],"classLoaderModelLoaderDescriptor":{"id":"mule","attributes":{"exportedResources":[]}}}`)

	if err := rebuildMuleArtifact(project, app); err != nil {
		t.Fatal(err)
	}
	var artifact struct {
		Configs    []string `json:"configs"`
		Descriptor struct {
			Attributes struct {
				ExportedResources []string `json:"exportedResources"`
			} `json:"attributes"`
		} `json:"classLoaderModelLoaderDescriptor"`
	}
	if err := json.Unmarshal([]byte(readFile(t, app+"/META-INF/mule-artifact/mule-artifact.json")), &artifact); err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(artifact.Configs, []string{"flow.xml", "sub/other.xml"}) {
		t.Errorf("configs = %v", artifact.Configs)
	}
	want := []string{"flow.xml", "sub/other.xml", "app.properties"}
	if !reflect.DeepEqual(artifact.Descriptor.Attributes.ExportedResources, want) {
		t.Errorf("exportedResources = %v, want %v", artifact.Descriptor.Attributes.ExportedResources, want)
	}
}

func TestRebuildMuleArtifactMissingDescriptor(t *testing.T) {
	setOpts(t, defaultTestOpts())
	dir := t.TempDir()
	writeFile(t, dir+"/app/META-INF/mule-artifact/mule-artifact.json", `{"name":"x"}`)
	if err := rebuildMuleArtifact(dir+"/proj", dir+"/app"); err == nil {
		t.Error("missing classLoaderModelLoaderDescriptor must be an error")
	}
}

func TestCopyFilePreservesPermissions(t *testing.T) {
	dir := t.TempDir()
	src := dir + "/script.sh"
	writeFile(t, src, "#!/bin/sh\necho hi\n")
	if err := os.Chmod(src, 0o755); err != nil {
		t.Fatal(err)
	}
	dst := dir + "/copy.sh"
	if err := copyFile(src, dst); err != nil {
		t.Fatal(err)
	}
	if readFile(t, dst) != "#!/bin/sh\necho hi\n" {
		t.Error("content mismatch")
	}
	info, err := os.Stat(dst)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o755 {
		t.Errorf("permissions = %o, want 755", info.Mode().Perm())
	}
}

func TestEnsureAndRemoveTrailingSlash(t *testing.T) {
	if ensureTrailingSlash("/a/b") != "/a/b/" || ensureTrailingSlash("/a/b/") != "/a/b/" {
		t.Error("ensureTrailingSlash")
	}
	if removeTrailingSlash("/a/b/") != "/a/b" || removeTrailingSlash("/a/b") != "/a/b" {
		t.Error("removeTrailingSlash")
	}
}
