package main

import (
	"encoding/json"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"unicode"
)

func ensureTrailingSlash(path string) string {
	if strings.HasSuffix(path, "/") {
		return path
	}
	return path + "/"
}

func removeTrailingSlash(path string) string {
	return strings.TrimSuffix(path, "/")
}

var (
	appSubDirsRegex  = regexp.MustCompile(`/src/main/(mule|resources)(/.+)/[^/]+$`)
	projectRootRegex = regexp.MustCompile(`(.*)/src/main/(mule|resources)/`)
)

// appSubDirs matches the dirs after /src/main/mule|resources but before the file
func appSubDirs(path string) string {
	m := appSubDirsRegex.FindStringSubmatch(path)
	if m == nil {
		return ""
	}
	return ensureTrailingSlash(m[2])
}

func extractProjectRootFromPath(path string) string {
	m := projectRootRegex.FindStringSubmatch(path)
	if m == nil {
		fmt.Println("ERROR: Pattern not found in path")
		return ""
	}
	if opts.Verbose {
		fmt.Printf("Project root: %s\n", m[1])
	}
	return m[1]
}

func extractProjectNameFromPom(pomFile string, quiet bool) string {
	root, err := pomDocument(pomFile)
	if err != nil || root == nil {
		if !quiet {
			fmt.Printf("ERROR: Could not read pom.xml: %s\n", pomFile)
		}
		return ""
	}
	name := root.childText("name")
	if name == "" {
		if !quiet {
			fmt.Println("ERROR: No <name> element found in the pom.xml")
		}
		return ""
	}
	if opts.Verbose {
		fmt.Printf("Project Name: %s\n", name)
	}
	return name
}

func extractProjectNameFromFilepath(path string) string {
	projectRoot := extractProjectRootFromPath(path)
	if projectRoot == "" {
		return ""
	}
	return extractProjectNameFromPom(projectRoot+"/pom.xml", false)
}

func resourcesFile(filePath string) bool {
	return strings.Contains(filePath, "src/main/resources")
}

func log4j2File(filePath string) bool {
	return strings.EqualFold(filepath.Base(filePath), "log4j2.xml")
}

func containsMonitorInterval(filePath string) bool {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return false
	}
	root, err := parseXML(data)
	if err != nil || root == nil || root.XMLName.Local != "Configuration" {
		return false
	}
	for _, attr := range root.Attrs {
		if attr.Name.Local == "monitorInterval" {
			return true
		}
	}
	return false
}

func ignoreFile(file string) bool {
	// List of directory names or patterns to ignore
	ignores := []string{"target/", "bin/", ".mule/", "weave/autogenerated", ".git/"}
	// Only the path below the projects dir counts: a projects dir living
	// under e.g. /home/user/bin must not ignore every file in it
	checked := strings.TrimPrefix(file, ensureTrailingSlash(opts.ProjectsDir))
	ignored := strings.HasSuffix(checked, ".orig")
	for _, ignore := range ignores {
		if strings.Contains(checked, ignore) {
			ignored = true
			break
		}
	}
	if ignored && opts.Verbose {
		fmt.Printf("Ignoring %s\n", file)
	}
	return ignored
}

func appDeployed(appDir string) bool {
	if dirExists(appDir) {
		return true
	}
	if opts.Verbose {
		fmt.Printf("No app deployed in: %s Will not update\n", appDir)
	}
	return false
}

func dirExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}

func createDestinationSubDirsIfMissing(destinationDir string) {
	if !dirExists(destinationDir) {
		fmt.Printf("Created sub-dirs for %s\n", destinationDir)
		os.MkdirAll(destinationDir, 0o755)
	}
}

// significantChanges tests if the changes are more than XML/JSON formatting.
// Every other file type is compared exactly by default: whitespace can be
// semantically meaningful in .properties or DataWeave files. With
// --no-ignore-formatting XML/JSON are compared exactly too; the
// --ignore-whitespace/--ignore-blank-lines opt-ins relax the comparison for
// all file types (GNU diff -w/-B semantics).
func significantChanges(updatedFile, currentFile string) bool {
	updatedInfo, err := os.Stat(updatedFile)
	if err != nil {
		return true
	}
	currentInfo, err := os.Stat(currentFile)
	if err != nil {
		return true
	}
	// Files over 1MB are copied without comparison
	const sizeThreshold = 1 * 1024 * 1024
	if updatedInfo.Size() > sizeThreshold || currentInfo.Size() > sizeThreshold {
		return true
	}
	updatedData, err := os.ReadFile(updatedFile)
	if err != nil {
		fmt.Printf("Error diffing files: %v\n", err)
		return true
	}
	currentData, err := os.ReadFile(currentFile)
	if err != nil {
		fmt.Printf("Error diffing files: %v\n", err)
		return true
	}
	updatedContent := string(updatedData)
	currentContent := string(currentData)
	if opts.IgnoreFormatting {
		switch strings.ToLower(filepath.Ext(updatedFile)) {
		case ".xml":
			if opts.Verbose {
				fmt.Println("Canonicalizing XML before comparison")
			}
			u, uerr := canonicalizeXML(updatedData)
			c, cerr := canonicalizeXML(currentData)
			switch {
			case uerr == nil && cerr == nil:
				updatedContent, currentContent = u, c
			case uerr != nil && cerr == nil:
				// The updated file doesn't parse while the deployed copy
				// does: most likely a half-written save — keep the last
				// good deployed copy
				fmt.Printf("Error parsing XML: %v\n", uerr)
				return false
			default:
				// The deployed copy itself doesn't canonicalize (corrupt,
				// or an encoding we can't parse): fall back to exact
				// comparison so the file can still sync and repair it
				fmt.Printf("Error parsing XML: %v\n", firstError(uerr, cerr))
			}
		case ".json":
			if opts.Verbose {
				fmt.Println("Canonicalizing JSON before comparison")
			}
			u, uerr := canonicalizeJSON(updatedData)
			c, cerr := canonicalizeJSON(currentData)
			if uerr != nil || cerr != nil {
				fmt.Printf("Error parsing JSON: %v\n", firstError(uerr, cerr))
			} else {
				updatedContent, currentContent = u, c
			}
		}
	}
	if opts.IgnoreWhitespace || opts.IgnoreBlankLines {
		updatedContent = normalizeForDiff(updatedContent)
		currentContent = normalizeForDiff(currentContent)
	}
	changed := updatedContent != currentContent
	if opts.Verbose && changed {
		fmt.Println("Diff: files differ after comparison")
	}
	return changed
}

// normalizeForDiff applies the equivalent of GNU diff's -w (ignore all
// whitespace within lines) and -B (ignore blank lines) before comparing.
// GNU-faithful: -B alone drops only completely empty lines, and -w alone
// does not drop a new blank line; with both, whitespace-only lines have
// already become empty and so count as blank, like GNU diff.
func normalizeForDiff(content string) string {
	lines := strings.Split(content, "\n")
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		if opts.IgnoreWhitespace {
			line = strings.Map(func(r rune) rune {
				if unicode.IsSpace(r) {
					return -1
				}
				return r
			}, line)
		}
		if opts.IgnoreBlankLines && line == "" {
			continue
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

func firstError(errs ...error) error {
	for _, err := range errs {
		if err != nil {
			return err
		}
	}
	return nil
}

func canonicalizeJSON(data []byte) (string, error) {
	var parsed interface{}
	if err := json.Unmarshal(data, &parsed); err != nil {
		return "", err
	}
	out, err := json.MarshalIndent(parsed, "", "  ")
	if err != nil {
		return "", err
	}
	return string(out), nil
}

// rebuildMuleArtifact rewrites mule-artifact.json, which triggers a redeploy
func rebuildMuleArtifact(projectDir, appDir string) error {
	projectName := filepath.Base(removeTrailingSlash(projectDir))
	sendNotification("🔄", "Re-deploying: "+projectName)
	filePath := appDir + "/META-INF/mule-artifact/mule-artifact.json"
	jsonData, err := os.ReadFile(filePath)
	if err != nil {
		return err
	}
	var data map[string]interface{}
	if err := json.Unmarshal(jsonData, &data); err != nil {
		return err
	}

	muleXMLFiles, err := relativeFiles(projectDir+"/src/main/mule/", ".xml")
	if err != nil {
		return err
	}
	resourcesFiles, err := relativeFiles(projectDir+"/src/main/resources/", "")
	if err != nil {
		return err
	}

	data["configs"] = muleXMLFiles
	descriptor, ok := data["classLoaderModelLoaderDescriptor"].(map[string]interface{})
	if !ok {
		return fmt.Errorf("mule-artifact.json has no classLoaderModelLoaderDescriptor object")
	}
	attributes, ok := descriptor["attributes"].(map[string]interface{})
	if !ok {
		return fmt.Errorf("mule-artifact.json has no classLoaderModelLoaderDescriptor.attributes object")
	}
	attributes["exportedResources"] = append(append([]string{}, muleXMLFiles...), resourcesFiles...)

	out, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(filePath, out, 0o644); err != nil {
		return err
	}
	fmt.Println("Rebuilt mule-artifact.json")
	return nil
}

// relativeFiles lists the files under root (optionally restricted by
// extension) with paths relative to root
func relativeFiles(root, ext string) ([]string, error) {
	files := []string{}
	if !dirExists(root) {
		return files, nil
	}
	prefix := ensureTrailingSlash(filepath.ToSlash(filepath.Clean(root)))
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		// Dot-files and dot-directories are excluded like a shell glob,
		// keeping .DS_Store and friends out of mule-artifact.json
		if strings.HasPrefix(d.Name(), ".") && filepath.ToSlash(path) != removeTrailingSlash(prefix) {
			if d.IsDir() {
				return fs.SkipDir
			}
			return nil
		}
		if d.IsDir() {
			return nil
		}
		if ext != "" && filepath.Ext(path) != ext {
			return nil
		}
		files = append(files, strings.TrimPrefix(filepath.ToSlash(path), prefix))
		return nil
	})
	return files, err
}

// triggerRedeploy rewrites mule-artifact.json so Mule redeploys the app
func triggerRedeploy(projectRoot, appDir string) {
	if projectRoot == "" {
		return
	}
	if err := rebuildMuleArtifact(projectRoot, appDir); err != nil {
		fmt.Printf("ERROR rebuilding mule-artifact.json: %v\n", err)
	}
}

func handleFileChange(file, event string) {
	if ignoreFile(file) {
		return
	}
	projectName := extractProjectNameFromFilepath(file)
	if projectName == "" {
		if opts.Verbose {
			fmt.Printf("WARNING: Could not determine project name for: %s\n", file)
		}
		return
	}
	appDir := opts.AppsDir + "/" + projectName
	if !appDeployed(appDir) {
		return
	}

	switch event {
	case "modified", "added":
		destinationDir := appDir + "/" + appSubDirs(file)
		createDestinationSubDirsIfMissing(destinationDir)
		if opts.Verbose {
			fmt.Printf("Destination dir %s\n", destinationDir)
		}
		projectRoot := extractProjectRootFromPath(file)
		if dirExists(file) {
			if event == "added" {
				os.MkdirAll(destinationDir+"/"+filepath.Base(file), 0o755)
				fmt.Printf("Created directory: %s in %s\n", file, destinationDir)
				triggerRedeploy(projectRoot, appDir)
			} else if opts.Verbose {
				fmt.Printf("Skipping directory modification: %s\n", file)
			}
			return
		}
		withSourceFile(file, projectRoot, func(source string) {
			destination := destinationDir + "/" + filepath.Base(file)
			if event == "modified" && !significantChanges(source, destination) {
				fmt.Println("No significant change, will not update")
				return
			}
			if err := copyFile(source, destination); err != nil {
				fmt.Printf("ERROR copying %s: %v\n", file, err)
				return
			}
			verb := "Updated"
			if event == "added" {
				verb = "Added"
			}
			fmt.Printf("%s: %s in %s\n", verb, file, destinationDir)
			if log4j2File(file) && containsMonitorInterval(file) {
				fmt.Println("Skipping forced re-deploy because log4j2.xml contains monitorInterval")
			} else {
				triggerRedeploy(projectRoot, appDir)
			}
		})

	case "removed":
		destinationDir := appDir + appSubDirs(file)
		deletePath := destinationDir + "/" + filepath.Base(file)
		if dirExists(deletePath) {
			os.RemoveAll(deletePath)
			fmt.Printf("Removed directory: %s\n", deletePath)
		} else if fileExists(deletePath) {
			os.Remove(deletePath)
			fmt.Printf("Removed: %s\n", deletePath)
		}
		projectRoot := extractProjectRootFromPath(file)
		triggerRedeploy(projectRoot, appDir)
	}
}

// handleFileChangeSafely never lets one file's failure abort the rest of a change batch
func handleFileChangeSafely(file, event string) {
	defer func() {
		if r := recover(); r != nil {
			fmt.Printf("ERROR processing file %s: %v\n", file, r)
		}
	}()
	handleFileChange(file, event)
}

// copyFile streams src to dst; a newly created dst gets src's permissions
// (so e.g. exec bits survive), an existing dst keeps its own
func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	info, err := in.Stat()
	if err != nil {
		return err
	}
	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, info.Mode().Perm())
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		return err
	}
	return out.Close()
}
